### ISSUE TITLE
Check if connection can be established before adding account or opening the Imap window

### ISSUE THREAD

**Issue by ClayGee** [hpi-swa-teaching/IMAPClient#127]
When we close and reopen the imap client, the user gets asked for the password of every previously added account. At this point and when adding an account, we do not have a mechanism that immidiately checks if a connection can be established, before the account is added.

**Comment by davidhennemann** [comment]
For this i would recommend that the `ICPasswordDialog` creates an ICEndpoint, and checks whether that is logged in ( i think otherwise it would throw an error ...), if everything worked fine, we should just pass the endpoint, which was created by the `ICPasswordDialog`, to the callback function within the `ICFolderDialog>>addPasswordToCollection: aDictionary`. Of course it would need quite some refactoring, because  at the moment the `ICFolderDialog` method currently expects an Dictionary, and will create all the endpoints at the end of the "asking-for-password"-process. We maybe should change that, so that the Method accepts an Endpoint :)

**Comment by felixrindt** [comment]
Cannot reproduce. After entering a password without internet connect, I get a "Can't connect to server" Note, as expected.
