### ISSUE TITLE
Arrow key navigation

### ISSUE THREAD

**Issue by ClayGee** [hpi-swa-teaching/IMAPClient#152]

**Comment by EightSQ** [comment]
Pressing the _up or left arrow key_ with the top list item selected leads to open the email. This seems like unexpected behaviour.

Opening the selected email by pressing _enter_ should be a feature.

**Comment by Paulpanther** [comment]
**Double click fix**
Before the fix in #186 emails could only be opened by double clicking. The action got called when `#selectedEmail:` got called on a selected email (Selecting it twice in a row). This created the problem that pressing *Up* at the Email at the top opened it, because it got selected when it was already selected. We removed this behavior and instead called `#openEmail:` directly by passing it to the `#doubleClick` method of the TreeSpec.

**Comment by Paulpanther** [comment]
**Why open Emails with key `o`?**
The list is implemented with a `PluggableTreeMorph`, which uses *Enter* to reset its filter. All other ToolBuilder-Morphs which provide list-behavior do the same. Since *Right* gets captured too, we decided to use `$o`. The letter can be changed in `ICFolderDialog class defaultOpenEmailChar`

**Comment by felixrindt** [comment]
We had the idea of rebuilding the account and email list closer to how the code browser is implemented, since that behavior is much more natural for the Squeak ToolBuilder. In the same manner, dirty hacks like the "Click email to load more email" could be reworked.
