### ISSUE TITLE
DNU when tabbing between fields in IMAP Login dialog

### ISSUE THREAD

**Issue by tcj** [hpi-swa-teaching/IMAPClient#221]
I loaded this into a new 5.2 image, and opened it as follows:

`ICLoginDialog open: ICFolderDialog new`

In the login dialog, I entered my name and then hit 'tab' to move to the next field.  I was presented with this:

![Screen Shot 2019-06-18 at 4 01 50 PM](https://user-images.githubusercontent.com/2293335/59725512-b5c90f80-91e2-11e9-88ef-7d10f9418db4.png)

**Comment by Paulpanther** [comment]
I asked @tom95 about this. This is caused by missing packages. Since we should not depend on them we could rewrite this. Tom send me this line: `anEvent hand newKeyboardFocus: self` (Could contain typos), but I didn't look into further. We can contact Tom for more info. (@tcj fyi: @martintaraz, @EightSQ, @EatingBacon, @felixrindt and I are currently working on this project)

**Comment by shm0sby** [comment]
Closed because not reproducible in Linux and Windows on Squeak version 5.3
