### ISSUE TITLE
Remove folders unnecessary to the IMAP window 

### ISSUE THREAD

**Issue by ClayGee** [hpi-swa-teaching/IMAPClient#74]
Do not display: Tasks, Notes, Outbox, Journal, Check, Info, Items, Contacts

**Comment by davidhennemann** [comment]
This is kina hard to do. Because the folder can have different names depending on the mail account. 
On my Gmail these folder will have other names than on my HPI-OWA. So hiding folders named "Tasks" or "Notes" wont work. Also it might be a problem e.g. if someone has a Folder "Tasks" in his Mail Account, where he moves his to-do Mails. This shouldnt be hidden only because the Folder name matches our hiding rule. I would suggest to auto-hide folder, which do not contain any email data. But i am not sure how to implement this and how to differentiate between a calender and a mail file.

**Comment by ClayGee** [comment]
Yes you're right. Maybe we can look at this together as a team once and decide how to implement this.
But I think it would be important to do, because it isn't a good user experience to expect something to work, because it is clearly displayed there, even though it does not work.

**Comment by felixrindt** [comment]
Because of how different Email Providers name their folders, this issue was replaced by the more broad issue #169.
